# Generated by Django 4.2.4 on 2023-08-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customerinvoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('created, not paid', 'created, not paid'), ('created, paid', 'created, paid'), ('created, timeouted', 'created, timeouted')], default=1, max_length=50),
        ),
    ]
