# Generated by Django 4.2.4 on 2023-08-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[(1, 'created, not paid'), (2, 'created, paid'), (2, 'created, timeouted')], default=1, max_length=50),
        ),
    ]
