# Generated by Django 4.2.4 on 2023-08-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='invoices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('1', 'created, not paid'), ('2', 'created, paid'), ('3', 'created, timeouted')], default='1', max_length=50),
        ),
        migrations.DeleteModel(
            name='CustomerInvoices',
        ),
    ]
