# Generated by Django 4.1.3 on 2023-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customer_invoices_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='invoices',
        ),
        migrations.AddField(
            model_name='customer',
            name='invoices',
            field=models.ManyToManyField(blank=True, null=True, to='api.invoice'),
        ),
    ]
