# Generated by Django 4.1.3 on 2023-08-04 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customer_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='invoices',
        ),
        migrations.AddField(
            model_name='customer',
            name='invoices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.invoice'),
        ),
    ]
