# Generated by Django 4.1.3 on 2023-08-06 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_customer_invoices_customer_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='invoices',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='api.customer'),
        ),
    ]
