# Generated by Django 4.2.4 on 2023-08-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_invoice_currency_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
